### ISSUE TITLE
timeseriesweka.filters.measures

### ISSUE THREAD

**Issue by TonyBagnall** [goastler/uea-tsc#17]
is this used/necessary?
![image](https://user-images.githubusercontent.com/9594042/52332619-10f82380-29f3-11e9-90bc-67d6356f14d0.png)

**Comment by goastler** [comment]
Well, kind of. DistanceMeasure is the generic abstract distance measure class implemented by all distance measures (i.e. just functions for getting distance between two instances / double arrays). TAA is the attempted implementation of the TAA algorithm @TonyBagnall asked me to look at, but it doesn't work and with no reply from the author I doubt it will ever work. We can get rid of the taa package in which case

**Comment by TonyBagnall** [comment]
ok could you move DistanceMeasures somewhere better and remove TAA from the master repo? Just keep a local copy I feel, we could try again but probably not work it.

**Comment by goastler** [comment]
Added to to-do list

**Comment by goastler** [comment]
TAA failed due to index out of bounds. Can't work out what it's trying to do, but can show you the loop with the error if you like. It's the first loop in TAA so pretty quick bug, and because it's poorly coded / documented I can't see what it's meant to do / how to fix it. Could do with the author's help tbh

**Comment by TonyBagnall** [comment]
can take a look tomorrow maybe
